sleighxmas/Assets/Art/Grinch_material.mat, sleighxmas/Assets/Art/Grinch_material.mat.meta, sleighxmas/Assets/Art/Santa_color.mat, sleighxmas/Assets/Art/Santa_color.mat.meta, sleighxmas/Assets/Scenes/Level1.unity, sleighxmas/Assets/Scenes/test-level.unity, sleighxmas/Assets/Scenes/test-level.unity.meta
=> Split screen

sleighxmas/Assets/Scenes/TestScene.unity, sleighxmas/Assets/Scripts/MultiPlayerMoveAround.cs
Gifts now disappear when touched and a chime is sounded when they are collided with
=> Gifts & Sound

sleighxmas/Assets/Prefabs/Player1.prefab, sleighxmas/Assets/Scenes/TestScene.unity, sleighxmas/Assets/Scripts/MultiPlayerMoveAround.cs
adde individual jumps and increased force
=> added-ind-j

sleighxmas/Assets/Scenes/Level1.unity, sleighxmas/ProjectSettings/EditorBuildSettings.asset
=> added-tiles

sleighxmas/Assets/Scripts/MultiPlayerMoveAround.cs, sleighxmas/ProjectSettings/InputManager.asset
technically added xbox space button. dk if it works
=> button xbox

sleighxmas/Assets/Scenes/EndPage.unity, sleighxmas/Assets/Scenes/Level1.unity
the tree is there but doesn't have code to be triggered
=> started collision to end scene

sleighxmas/Assets/Scenes/Level2.unity, sleighxmas/Assets/Scenes/Level2.unity.meta, sleighxmas/Assets/Scenes/Level3.unity, sleighxmas/Assets/Scenes/Level3.unity.meta, sleighxmas/Assets/Scenes/Level4.unity, sleighxmas/Assets/Scenes/Level4.unity.meta, sleighxmas/Assets/Scenes/Level5.unity, sleighxmas/Assets/Scenes/Level5.unity.meta
just duplicated the levels.
next up: connecting them
=> added levels

sleighxmas/Assets/Scenes/Level2.unity
placed candy cane tiles for level 2
=> candy cane tiles

sleighxmas/Assets/Scenes/Level1.unity
added more corner tiles to level 1
=> more tiles

sleighxmas/Assets/Scripts/MultiPlayerMoveAround.cs, sleighxmas/ProjectSettings/EditorBuildSettings.asset
slay the scenes minus the front page are all connected!
=> connected scenes

sleighxmas/Assets/Scenes/StartPage.unity
added text objects and made them children of a game object. used them as placeholders!
=> connected-all-scenes

sleighxmas/Assets/Scripts/MultiPlayerMoveAround.cs, sleighxmas/ProjectSettings/EditorBuildSettings.asset
add 3 points to whoever reaches tree first
=> add 3 point

sleighxmas/Assets/Scenes/EndPage.unity, sleighxmas/Assets/Scenes/Level3.unity, sleighxmas/Assets/Scenes/StartPage.unity, sleighxmas/Assets/Scripts/TimerScript.cs, sleighxmas/Assets/Scripts/TimerScript.cs.meta, sleighxmas/ProjectSettings/EditorBuildSettings.asset
first screen and end game was wrongly scaled. timer is disabled bc it doesnt freeze players yet.
=> added timer and fixed screen

sleighxmas/Assets/Scenes/Instructions.unity
=> added background

sleighxmas/Assets/Scenes/Level1.unity, sleighxmas/Assets/Scripts/GameHandler.cs
now the score gets passed on to every level!
=> static variables

sleighxmas/Assets/Scenes/Instructions.unity, sleighxmas/Assets/Scenes/Level1.unity, sleighxmas/Assets/Scenes/Level2.unity, sleighxmas/Assets/Scenes/Level3.unity, sleighxmas/Assets/Scenes/Level4.unity, sleighxmas/Assets/Scenes/Level5.unity
added the timer to every scene and changed the second from 6 to 3. also fixed the tree on level 1. and the instructions.
=> added-timer-scenes

sleighxmas/Assets/Art/Player1_santa 1.controller, sleighxmas/Assets/Art/Player1_santa 1.controller.meta, sleighxmas/Assets/Art/Player1_santa.controller, sleighxmas/Assets/Art/Player1_santa.controller.meta, sleighxmas/Assets/Art/santa_idle.anim, sleighxmas/Assets/Art/santa_idle.anim.meta, sleighxmas/Assets/Art/santa_punch.anim, sleighxmas/Assets/Art/santa_punch.anim.meta, sleighxmas/Assets/Prefabs/Player1_santa.prefab, sleighxmas/Assets/Prefabs/Player1_santa.prefab.meta, sleighxmas/Assets/Prefabs/Player2_grinch.prefab, sleighxmas/Assets/Prefabs/Player2_grinch.prefab.meta, sleighxmas/Assets/Scenes/Level1.unity, sleighxmas/Assets/Scripts/MultiPlayerMoveAround.cs
added in art for punches, and implemented in animator, up until adding conditions for santa, and creating transitions for grinch
=> progress on animation

sleighxmas/Assets/Art/grinch-idle.anim, sleighxmas/Assets/Art/grinch-idle.anim.meta, sleighxmas/Assets/Art/grinch-punch.anim, sleighxmas/Assets/Art/grinch-punch.anim.meta, sleighxmas/Assets/Art/grinchArt.controller, sleighxmas/Assets/Art/grinchArt.controller.meta, sleighxmas/Assets/Art/new-san-punch.anim, sleighxmas/Assets/Art/new-san-punch.anim.meta, sleighxmas/Assets/Art/new-santa2.anim, sleighxmas/Assets/Art/new-santa2.anim.meta, sleighxmas/Assets/Art/santa-new.anim, sleighxmas/Assets/Art/santa-new.anim.meta, sleighxmas/Assets/Art/santa_punch_0.controller, sleighxmas/Assets/Art/santa_punch_0.controller.meta, sleighxmas/Assets/Prefabs/Player1_santa.prefab, sleighxmas/Assets/Prefabs/Player2_grinch.prefab, sleighxmas/Assets/Scenes/GrinchWin.unity, sleighxmas/Assets/Scenes/Level1.unity, sleighxmas/Assets/Scenes/Level2.unity, sleighxmas/Assets/Scenes/Level3.unity, sleighxmas/Assets/Scenes/Level4.unity, sleighxmas/Assets/Scenes/Level5.unity, sleighxmas/Assets/Scenes/SantaWin.unity, sleighxmas/Assets/Scripts/GameHandler.cs, sleighxmas/Assets/Scripts/PlayerMeleeAttack.cs
added animation to punch. reset scores when hit play again. set place holders of win scenes. removed gifts from a scene that were overlayed
=> added animation to punch

sleighxmas/Assets/Prefabs/Player1_santa.prefab, sleighxmas/Assets/Prefabs/Player2_grinch.prefab, sleighxmas/Assets/Prefabs/treePrefab.prefab, sleighxmas/Assets/Prefabs/treePrefab.prefab.meta, sleighxmas/Assets/Scenes/Level5.unity, sleighxmas/Assets/Scripts/PlayerMeleeAttack.cs, sleighxmas/Assets/Scripts/PlayerMeleeAttack.cs.meta, sleighxmas/Assets/Scripts/dropItem.cs, sleighxmas/Assets/Scripts/dropItem.cs.meta
Added code so that it should spawn in a gift if someone can connect the list in the script to a list of each item
=> gift progress

sleighxmas/Assets/Scenes/Level1.unity, sleighxmas/Assets/Scenes/Level2.unity, sleighxmas/Assets/Scenes/Level3.unity, sleighxmas/Assets/Scenes/Level4.unity, sleighxmas/Assets/Scenes/Level5.unity, sleighxmas/Assets/Scripts/GameHandler.cs, sleighxmas/Assets/Scripts/PlayerMeleeAttack.cs, sleighxmas/Assets/Scripts/dropItem.cs
fixed belle's code that respawned gifts!!!
=> gift-respawn
